application: d4ngu357800k
version: 0-5
runtime: python
api_version: 1

handlers:
- url: /check-in/*
  script: web_interface/print_check_in.py

- url: /users/*
  script: web_interface/print_users.py
  
- url: /reports/*
  script: web_interface/print_reports.py
  
- url: /get/fares.*
  script: json_downloaders/fares.py
  
- url: /get/distances/*
  script: json_downloaders/display_distances_between_stations.py
  
- url: /get/tube-lines-status/*
  script: json_downloaders/tube_lines_status.py
  
- url: /posted/here.*
  script: test_uploader/testing.py
  
- url: /upload/post/*
  script: test_uploader/receive_communique.py
  
- url: /upload/csv/*
  script: test_uploader/receive_logs.py
  
- url: /delete/logs/*
  script: data/delete.py
  
- url: /.*
  script: home.py
  
builtins:
- datastore_admin: on
- remote_api: on

inbound_services:
- channel_presence
