application: tubeserver
version: 0-test
runtime: python
api_version: 1

handlers:
- url: /check-in/*
  script: web_interface/print_check_in.py

- url: /users/*
  script: web_interface/print_users.py
  
- url: /users/.*
  script: testing_one_two_three.py
  
- url: /reports/*
  script: web_interface/print_reports.py
  
- url: /reports/.*
  script: testing_part_two.py
  
- url: /get/fares/*
  script: json_downloaders/fares.py
  
- url: /get/tube-lines-status/*
  script: json_downloaders/tube_lines_status.py
  
- url: /posted/here.*
  script: test_uploader/testing.py
  
- url: /.*
  script: home.py
  
builtins:
- datastore_admin: on